/**
 * 疗愈馆样例数据
 * 包含丰富的筛选维度：类别、价格、形式、专业等级、来源平台
 */

const sampleResources = [
  {
    _id: 'res_001',
    name: 'Thanks绘画心理艺术工作室',
    description: '专注绘画艺术疗愈，提供曼陀罗绘画、自由创作、情绪表达等课程。拥有国际认证艺术疗愈师团队，环境温馨舒适，配备专业画材，为个人及团体提供定制化疗愈方案。',
    address_text: '上海市静安区愚园路309号3楼',
    district: '静安区',
    city: '上海',
    ratingNum: 4.9,
    review_count: 56,
    tags: ['绘画疗愈', '曼陀罗', '情绪表达'],
    therapy_categories: ['绘画疗愈'],
    formats: ['工作坊', '1v1', '企业团建'],
    price_min: 198,
    price_max: 688,
    price_text: '¥198-688/次',
    price_range: 'mid',
    certification_level: 'certified',
    certifications: ['IEATA国际认证', '中国心理学会注册'],
    source_platforms: ['dianping', 'partner'],
    is_exclusive_partner: true,
    cover_images: ['https://picui.ogmua.cn/s1/2026/03/07/69ab9e109468e.webp'],
    contact_info: { phone: '13812345678', wechat: 'bindraw_studio' },
    therapist_name: '林心怡',
    therapist_intro: '国际认证表达性艺术治疗师，8年绘画疗愈经验，擅长通过绘画帮助来访者表达和处理情绪。曾任职多家心理咨询中心。',
    feature_tags: ['环境优美', '适合新手', '可定制课程', '提供画材'],
    mood_tags: ['减压', '焦虑缓解', '自我探索'],
    per_person: 298,
    packages: [
      { name: '体验工作坊', price: 198, unit: '人', desc: '2小时绘画疗愈，含全套画材', hot: true },
      { name: '1v1定制课', price: 688, unit: '次', desc: '90分钟个性化疗愈方案' },
      { name: '企业团建', price: 168, unit: '人', desc: '20人起，含课程定制', tag: '企业' },
    ],
    resource_type: 'studio',
    sort_weight: 100,
    likes_count: 234,
  },
  {
    _id: 'res_002',
    name: '共振岛Echo Isle·手碟艺术疗愈',
    description: '沉浸式音疗体验空间，结合颂钵、手碟、自然声景等多种音疗方式。专业音疗师引导，帮助深度放松、改善睡眠、释放压力。每周定期沙龙，也接受1v1私人定制。',
    address_text: '上海市徐汇区武康路118号B1',
    district: '徐汇区',
    city: '上海',
    ratingNum: 4.8,
    review_count: 89,
    tags: ['音乐疗愈', '颂钵', '冥想'],
    therapy_categories: ['音乐疗愈', '颂钵音疗'],
    formats: ['沙龙', '1v1'],
    price_min: 128,
    price_max: 388,
    price_text: '¥128-388/次',
    price_range: 'mid',
    certification_level: 'experienced',
    certifications: ['美国音乐治疗协会认证'],
    source_platforms: ['dianping'],
    is_exclusive_partner: false,
    cover_images: ['https://picui.ogmua.cn/s1/2026/03/07/69ab9edb97ed0.webp'],
    contact_info: { phone: '15721188590', wechat: 'wanting_sound' },
    therapist_name: '陈雨薇',
    therapist_intro: '5年音疗经验，美国音乐治疗协会认证。专注颂钵与声音浴疗愈，帮助数百位来访者改善睡眠与情绪问题。',
    feature_tags: ['沉浸体验', '改善睡眠', '深度放松', '适合新手'],
    mood_tags: ['失眠', '减压', '情绪低落'],
    per_person: 188,
    packages: [
      { name: '沙龙音疗', price: 128, unit: '人', desc: '90分钟集体声音浴体验', hot: true },
      { name: '1v1私人音疗', price: 388, unit: '次', desc: '60分钟定制颂钵+手碟疗愈' },
    ],
    resource_type: 'studio',
    sort_weight: 95,
    likes_count: 312,
  },
  {
    _id: 'res_003',
    name: '芯泉舞蹈',
    description: '通过舞动与身体表达探索内心世界。不需要舞蹈基础，在安全的空间中自由移动身体，释放被压抑的情绪。定期开设舞动疗愈工作坊和体验沙龙，适合所有人群。',
    address_text: '上海市长宁区定西路1277号',
    district: '长宁区',
    city: '上海',
    ratingNum: 4.7,
    review_count: 38,
    tags: ['舞动疗愈', '身体表达', '情绪释放'],
    therapy_categories: ['舞动疗愈'],
    formats: ['工作坊', '沙龙'],
    price_min: 168,
    price_max: 468,
    price_text: '¥168-468/次',
    price_range: 'mid',
    certification_level: 'certified',
    certifications: ['美国舞动治疗协会(ADTA)注册', '心理咨询师二级'],
    source_platforms: ['xiaohongshu', 'partner'],
    is_exclusive_partner: true,
    cover_images: ['https://picui.ogmua.cn/s1/2026/03/07/69ab9f8c1b098.webp'],
    contact_info: { phone: '13698765432', wechat: 'zizai_dance' },
    therapist_name: '苏小曼',
    therapist_intro: '美国舞动治疗协会注册舞动治疗师，10年临床经验。相信身体是心灵的镜子，每一次舞动都是与自己的对话。',
    feature_tags: ['零基础友好', '安全空间', '身心整合', '小班教学'],
    mood_tags: ['情绪压抑', '身体紧张', '自我表达困难'],
    per_person: 228,
    packages: [
      { name: '入门体验课', price: 168, unit: '人', desc: '2小时舞动疗愈入门体验', hot: true },
      { name: '深度工作坊', price: 288, unit: '人', desc: '全天深度舞动体验（含餐）' },
      { name: 'VIP小班沙龙', price: 468, unit: '人', desc: '精品小班，限8人' },
    ],
    resource_type: 'studio',
    sort_weight: 90,
    likes_count: 156,
  },
  {
    _id: 'res_004',
    name: '人生剧本·爱情·艺术疗愈',
    description: '通过戏剧、即兴表演和角色扮演来探索自我、处理关系议题。适合希望以创造性方式解决人际困境的人。提供企业团建定制服务，帮助团队提升沟通与协作能力。',
    address_text: '上海市黄浦区局门路436号2层',
    district: '黄浦区',
    city: '上海',
    ratingNum: 4.8,
    review_count: 27,
    tags: ['戏剧疗愈', '即兴表演', '角色扮演'],
    therapy_categories: ['戏剧疗愈'],
    formats: ['工作坊', '企业团建'],
    price_min: 288,
    price_max: 1280,
    price_text: '¥288-1280/次',
    price_range: 'high',
    certification_level: 'certified',
    certifications: ['英国戏剧治疗师协会认证', '心理学硕士'],
    source_platforms: ['partner'],
    is_exclusive_partner: true,
    cover_images: ['https://picui.ogmua.cn/s1/2026/03/07/69ab9ff1e3420.webp'],
    contact_info: { phone: '18912345678', wechat: 'guangying_drama' },
    therapist_name: '赵一鸣',
    therapist_intro: '英国戏剧治疗硕士，曾在伦敦多家NHS机构从事戏剧治疗工作。回国后致力于推广戏剧疗愈在企业和个人成长中的应用。',
    feature_tags: ['创意十足', '团队协作', '深度体验', '专业导师'],
    mood_tags: ['人际困境', '自信不足', '表达障碍'],
    per_person: 480,
    packages: [
      { name: '半日戏剧体验', price: 288, unit: '人', desc: '半天即兴表演探索工作坊', hot: true },
      { name: '全日深度工作坊', price: 680, unit: '人', desc: '全天角色扮演与自我探索' },
      { name: '企业团建定制', price: 238, unit: '人', desc: '20人起，含互动设计', tag: '企业' },
    ],
    resource_type: 'workshop',
    sort_weight: 85,
    likes_count: 98,
  },
  {
    _id: 'res_005',
    name: '心尖儿心理疗愈空间iHeartspace',
    description: '名校F4团队，具有家庭氛围的疗愈空间，提供心理咨询沙龙或是1v1咨询服务，陪伴你找到内心的答案。',
    address_text: '徐家汇街道文定路218号B230',
    district: '徐家汇',
    city: '上海',
    ratingNum: 3.7,
    review_count: 112,
    tags: ['心理咨询', '疗愈空间', '正念冥想','颂钵疗愈'],
    therapy_categories: ['心理咨询','冥想正念','颂钵音疗'],
    formats: ['沙龙', '1v1'],
    price_min: 221,
    price_max: 1000,
    price_text: '¥221-1000/次',
    price_range: 'high',
    certification_level: 'experienced',
    certifications: ['心理名校F4咨询导师'],
    source_platforms: ['dianping'],
    is_exclusive_partner: false,
    cover_images: ['https://picui.ogmua.cn/s1/2026/03/07/69aba0a22e078.webp'],
    contact_info: { phone: '021-58889999', wechat: 'jingxin_meditate' },
    therapist_name: '王静心',
    therapist_intro: 'MBSR正念减压认证教师，15年冥想修行者。曾在泰国清迈修行3年，将东方禅修与西方正念科学相结合。',
    feature_tags: ['每日开放', '有免费体验', '线上同步', '适合入门'],
    mood_tags: ['焦虑', '失眠', '注意力涣散', '减压'],
    per_person: 382,
    packages: [
      { name: '沙龙体验课', price: 221, unit: '人', desc: '团体心理咨询沙龙', hot: true },
      { name: '1v1疗愈咨询', price: 600, unit: '次', desc: '60分钟个人疗愈咨询' },
      { name: '深度心理咨询', price: 1000, unit: '次', desc: '90分钟深度心理支持' },
    ],
    resource_type: 'studio',
    sort_weight: 88,
    likes_count: 567,
  },
  {
    _id: 'res_006',
    name: '芳华·芳香疗愈SPA',
    description: '高端芳香疗愈体验，甄选全球优质天然精油，结合芳疗按摩、精油调制、嗅觉冥想等方式，从身体层面舒缓紧张与疲劳。独立私密包间，一对一专属服务。',
    address_text: '上海市黄浦区淮海中路300号K11 B2',
    district: '黄浦区',
    city: '上海',
    ratingNum: 4.9,
    review_count: 73,
    tags: ['芳香疗愈', 'SPA', '精油按摩'],
    therapy_categories: ['芳香疗愈'],
    formats: ['1v1'],
    price_min: 388,
    price_max: 1288,
    price_text: '¥388-1288/次',
    price_range: 'high',
    certification_level: 'experienced',
    certifications: ['IFA国际芳疗师认证', 'NAHA认证'],
    source_platforms: ['dianping'],
    is_exclusive_partner: false,
    cover_images: [],
    contact_info: { phone: '021-63889988', wechat: '' },
    therapist_name: '张芳华',
    therapist_intro: 'IFA国际认证芳疗师，10年高端SPA管理经验。精通200+种植物精油的疗愈功效与调配方法。',
    feature_tags: ['高端私密', '天然精油', '身心放松', '独立包间'],
    mood_tags: ['身体疲劳', '减压', '情绪焦躁'],
    per_person: 688,
    packages: [
      { name: '基础芳疗 60min', price: 388, unit: '次', desc: '全身芳疗按摩+定制精油', hot: true },
      { name: '升级疗愈 90min', price: 688, unit: '次', desc: '精油调制+芳疗+嗅觉冥想' },
      { name: '尊享套餐 120min', price: 1288, unit: '次', desc: '顶级精油·全流程身心疗愈' },
    ],
    resource_type: 'studio',
    sort_weight: 82,
    likes_count: 189,
  },
  {
    _id: 'res_007',
    name: '暖光沐艺术疗愈室·正念塔罗·水晶芳疗',
    description: '专业塔罗牌解读与心灵指引。每位塔罗师均有心理学背景，将塔罗作为心灵沟通的工具而非算命。提供事业、感情、人生方向等主题的深度解读。',
    address_text: '上海市静安区南京西路1601号',
    district: '静安区',
    city: '上海',
    ratingNum: 4.5,
    review_count: 145,
    tags: ['塔罗占卜', '心灵指引', '自我探索'],
    therapy_categories: ['塔罗占卜'],
    formats: ['1v1', '线上课程'],
    price_min: 168,
    price_max: 588,
    price_text: '¥168-588/次',
    price_range: 'mid',
    certification_level: 'experienced',
    certifications: ['专业塔罗师认证', '心理咨询师三级'],
    source_platforms: ['xiaohongshu'],
    is_exclusive_partner: false,
    cover_images: ['https://picui.ogmua.cn/s1/2026/03/07/69ab9e0b93e3c.webp'],
    contact_info: { phone: '', wechat: 'xingyu_tarot' },
    therapist_name: '李星月',
    therapist_intro: '8年塔罗解读经验，累计服务2000+人次。心理学专业背景，注重塔罗的心理疗愈功能而非预测。',
    feature_tags: ['心理学背景', '深度解读', '线上可约', '好评如潮'],
    mood_tags: ['迷茫', '选择困难', '人生方向'],
    per_person: 288,
    packages: [
      { name: '线上塔罗解读', price: 168, unit: '次', desc: '60分钟视频深度解读', hot: true },
      { name: '线下面对面', price: 288, unit: '次', desc: '90分钟当面咨询解读' },
      { name: '专题深度解读', price: 588, unit: '次', desc: '两小时心理+塔罗综合咨询' },
    ],
    resource_type: 'studio',
    sort_weight: 75,
    likes_count: 423,
  },
  {
    _id: 'res_008',
    name: '禅境·瑜伽疗愈馆',
    description: '融合传统瑜伽与现代身心疗愈理念。提供修复瑜伽、阴瑜伽、瑜伽尼德拉等疗愈性课程。专注于通过体式与呼吸帮助练习者释放深层身心紧张，恢复内在平衡。',
    address_text: '上海市徐汇区衡山路890号',
    district: '徐汇区',
    city: '上海',
    ratingNum: 4.7,
    review_count: 68,
    tags: ['瑜伽', '修复瑜伽', '阴瑜伽'],
    therapy_categories: ['瑜伽'],
    formats: ['沙龙', '1v1', '企业团建'],
    price_min: 98,
    price_max: 398,
    price_text: '¥98-398/次',
    price_range: 'low',
    certification_level: 'certified',
    certifications: ['RYT-500国际瑜伽教师', '瑜伽治疗师认证'],
    source_platforms: ['dianping', 'partner'],
    is_exclusive_partner: false,
    cover_images: [],
    contact_info: { phone: '13501234567', wechat: 'chanjing_yoga' },
    therapist_name: '周静怡',
    therapist_intro: 'RYT-500认证瑜伽教师，瑜伽治疗师。深耕修复瑜伽领域6年，帮助许多学员改善了慢性疼痛和睡眠问题。',
    feature_tags: ['小班精品', '修复为主', '零基础友好', '冥想结合'],
    mood_tags: ['身体紧张', '慢性疲劳', '失眠', '情绪平衡'],
    per_person: 168,
    packages: [
      { name: '单次体验课', price: 98, unit: '次', desc: '75分钟修复/阴瑜伽体验', hot: true },
      { name: '小班精品课', price: 198, unit: '次', desc: '75分钟小班，限8人' },
      { name: '1v1私教课', price: 398, unit: '次', desc: '60分钟一对一定制' },
    ],
    resource_type: 'studio',
    sort_weight: 80,
    likes_count: 278,
  },
  {
    _id: 'res_009',
    name: '心悦·沙盘表达工作室',
    description: '运用沙盘游戏治疗和表达性艺术治疗，在安全的治疗关系中探索内心世界。由注册心理咨询师主持，适合情绪困扰、人际关系议题、个人成长等需求。',
    address_text: '上海市闵行区吴中路1189号',
    district: '闵行区',
    city: '上海',
    ratingNum: 4.8,
    review_count: 34,
    tags: ['心理咨询', '沙盘游戏', '表达性艺术'],
    therapy_categories: ['心理咨询'],
    formats: ['1v1'],
    price_min: 500,
    price_max: 800,
    price_text: '¥500-800/次',
    price_range: 'high',
    certification_level: 'certified',
    certifications: ['国家二级心理咨询师', '注册沙盘游戏治疗师'],
    source_platforms: ['partner'],
    is_exclusive_partner: true,
    cover_images: [],
    contact_info: { phone: '13712345678', wechat: 'xinyue_sandplay' },
    therapist_name: '刘思雨',
    therapist_intro: '国家二级心理咨询师，注册沙盘游戏治疗师。12年临床经验，专注儿童青少年与成人的沙盘治疗和表达性艺术治疗。',
    feature_tags: ['专业临床', '安全保密', '深度疗愈', '长程陪伴'],
    mood_tags: ['情绪困扰', '人际关系', '创伤修复', '自我探索'],
    per_person: 600,
    packages: [
      { name: '初次沙盘评估', price: 500, unit: '次', desc: '90分钟沙盘初次评估' },
      { name: '沙盘疗愈咨询', price: 600, unit: '次', desc: '60分钟个人沙盘疗愈', hot: true },
      { name: '深度长程疗愈', price: 800, unit: '次', desc: '90分钟深度沙盘+艺术整合' },
    ],
    resource_type: 'studio',
    sort_weight: 92,
    likes_count: 87,
  },
  {
    _id: 'res_010',
    name: '拾光·流体画艺术体验',
    description: '轻松有趣的流体画创作体验，让色彩自由流淌。不需要任何绘画基础，在创作过程中释放压力、获得当下的专注与愉悦。每周末开设体验沙龙，可带走自己的作品。',
    address_text: '上海市杨浦区大学路120号',
    district: '杨浦区',
    city: '上海',
    ratingNum: 4.6,
    review_count: 92,
    tags: ['绘画疗愈', '流体画', '创意体验'],
    therapy_categories: ['绘画疗愈'],
    formats: ['工作坊', '沙龙'],
    price_min: 88,
    price_max: 188,
    price_text: '¥88-188/次',
    price_range: 'low',
    certification_level: 'emerging',
    certifications: [],
    source_platforms: ['xiaohongshu', 'dianping'],
    is_exclusive_partner: false,
    cover_images: [],
    contact_info: { phone: '17612345678', wechat: 'shiguang_art' },
    therapist_name: '何小橙',
    therapist_intro: '青年艺术家，艺术教育背景。热衷于将艺术与疗愈结合，让更多人享受创作的快乐。',
    feature_tags: ['轻松有趣', '零基础', '可带走作品', '周末开放'],
    mood_tags: ['放松', '减压', '寻找乐趣'],
    per_person: 128,
    packages: [
      { name: '流体画体验', price: 88, unit: '人', desc: '90分钟创作+作品带走', hot: true },
      { name: '精品沙龙', price: 138, unit: '人', desc: '2小时小班，限10人' },
      { name: '亲子同乐', price: 188, unit: '人', desc: '亲子双人，一大一小' },
    ],
    resource_type: 'workshop',
    sort_weight: 70,
    likes_count: 456,
  },
  {
    _id: 'res_011',
    name: '回声·声音浴疗愈空间',
    description: '专业声音浴疗愈空间，使用水晶钵、铜钵、音叉、风铃等多种声疗器具。在声音的包围中进入深度冥想状态，体验身心的共振与疗愈。定期举办主题声音浴沙龙。',
    address_text: '上海市普陀区莫干山路50号',
    district: '普陀区',
    city: '上海',
    ratingNum: 4.9,
    review_count: 61,
    tags: ['音乐疗愈', '声音浴', '颂钵'],
    therapy_categories: ['音乐疗愈', '颂钵音疗'],
    formats: ['沙龙'],
    price_min: 198,
    price_max: 298,
    price_text: '¥198-298/次',
    price_range: 'mid',
    certification_level: 'certified',
    certifications: ['国际声疗师认证', '正念教师资格'],
    source_platforms: ['xiaohongshu', 'dianping'],
    is_exclusive_partner: false,
    cover_images: [],
    contact_info: { phone: '', wechat: 'huisheng_sound' },
    therapist_name: '许清音',
    therapist_intro: '国际认证声疗师，7年声音浴引导经验。在国内外举办过200+场声音浴活动，致力于推广声音疗愈文化。',
    feature_tags: ['沉浸体验', '多种器具', '场地独特', '小班制'],
    mood_tags: ['减压', '失眠', '深度放松', '灵性探索'],
    per_person: 238,
    packages: [
      { name: '普通座声音浴', price: 198, unit: '人', desc: '75分钟声音浴全程体验', hot: true },
      { name: 'VIP精华区', price: 298, unit: '人', desc: '最佳音效区，水晶钵正前方' },
    ],
    resource_type: 'studio',
    sort_weight: 86,
    likes_count: 345,
  },
  {
    _id: 'res_012',
    name: '张晓·独立疗愈师',
    description: '整合多种疗愈方式的独立执业疗愈师，根据每位来访者的独特需求定制个性化疗愈方案。擅长将艺术疗愈、身体工作、正念冥想等方式有机结合，陪伴深度自我探索。',
    address_text: '上海市徐汇区（预约后告知具体地址）',
    district: '徐汇区',
    city: '上海',
    ratingNum: 5.0,
    review_count: 18,
    tags: ['综合疗愈', '艺术疗愈', '正念'],
    therapy_categories: ['绘画疗愈', '冥想正念'],
    formats: ['1v1', '线上课程'],
    price_min: 600,
    price_max: 1500,
    price_text: '¥600-1500/次',
    price_range: 'premium',
    certification_level: 'certified',
    certifications: ['英国艺术治疗硕士', '国家二级心理咨询师', '正念教师认证'],
    source_platforms: ['partner'],
    is_exclusive_partner: true,
    cover_images: [],
    contact_info: { phone: '13912345678', wechat: 'zhangxiao_healer' },
    therapist_name: '张晓',
    therapist_intro: '英国艺术治疗硕士，国家二级心理咨询师。在英国和中国从事疗愈工作15年，整合艺术、身体与正念的疗愈方式。',
    feature_tags: ['深度定制', '长程陪伴', '多模态整合', '英国背景'],
    mood_tags: ['深度探索', '生命转折', '创伤修复', '灵性成长'],
    per_person: 800,
    packages: [
      { name: '艺术疗愈初探', price: 600, unit: '次', desc: '60分钟艺术疗愈探索' },
      { name: '整合疗愈', price: 800, unit: '次', desc: '90分钟多模态整合疗愈', hot: true },
      { name: '深度定制方案', price: 1500, unit: '次', desc: '120分钟深度长程疗愈' },
    ],
    resource_type: 'therapist',
    sort_weight: 98,
    likes_count: 67,
  },
  {
    _id: 'res_013',
    name: '共创·企业身心赋能项目',
    description: '专为企业设计的身心疗愈团建服务。包括艺术共创工作坊、团队舞动、正念领导力、压力管理等模块。已服务50+企业，帮助团队提升凝聚力与幸福感。',
    address_text: '上海市（可上门服务）',
    district: '',
    city: '上海',
    ratingNum: 4.8,
    review_count: 22,
    tags: ['企业团建', '艺术共创', '压力管理'],
    therapy_categories: ['绘画疗愈', '舞动疗愈', '冥想正念'],
    formats: ['企业团建'],
    price_min: 3000,
    price_max: 15000,
    price_text: '¥3000-15000/场',
    price_range: 'premium',
    certification_level: 'certified',
    certifications: ['多位认证疗愈师团队', '企业EAP服务经验'],
    source_platforms: ['partner'],
    is_exclusive_partner: true,
    cover_images: [],
    contact_info: { phone: '18812345678', wechat: 'gongchuang_corp' },
    therapists: [
      { name: '艾明远', title: '首席疗愈导师', intro: '艺术疗愈博士，企业身心赋能专家，曾服务腾讯、字节跳动等30+知名企业', certifications: ['IEATA国际认证艺术治疗师', '企业EAP高级督导'] },
      { name: '林秋月', title: '舞动疗愈师', intro: 'ADTA注册舞动治疗师，专注团队身体智能与情绪管理培训', certifications: ['ADTA美国舞动治疗注册'] },
      { name: '赵梓文', title: '正念领导力教练', intro: 'MBSR认证正念教师，ICF教练，帮助管理层发展领导力与抗压能力', certifications: ['MBSR正念减压认证教师', 'ICF国际注册教练'] },
    ],
    feature_tags: ['上门服务', '定制方案', '百人团建', '知名企业背书'],
    mood_tags: ['团队协作', '职场压力', '创意激发'],
    per_person: 300,
    packages: [
      { name: '半日艺术团建', price: 3000, unit: '场', desc: '4小时艺术共创+正念，20-50人', hot: true, tag: '企业' },
      { name: '全日赋能方案', price: 6000, unit: '场', desc: '8小时身心赋能，50-100人', tag: '企业' },
      { name: '两日沉浸营', price: 15000, unit: '场', desc: '36小时深度团建，百人规模', tag: '企业' },
    ],
    resource_type: 'workshop',
    sort_weight: 78,
    likes_count: 45,
  },
  {
    _id: 'res_014',
    name: '泥语·陶艺疗愈体验馆',
    description: '在泥土与双手的对话中感受当下。提供手工拉坯、泥塑创作等陶艺疗愈体验，在触觉与创造中找回内心的宁静。作品可烧制带走，留住疗愈的记忆。',
    address_text: '上海市浦东新区芳甸路199弄',
    district: '浦东新区',
    city: '上海',
    ratingNum: 4.7,
    review_count: 78,
    tags: ['陶艺疗愈', '手工创作', '减压'],
    therapy_categories: ['绘画疗愈'],
    formats: ['工作坊', '沙龙'],
    price_min: 128,
    price_max: 258,
    price_text: '¥128-258/次',
    price_range: 'low',
    certification_level: 'emerging',
    certifications: [],
    source_platforms: ['dianping', 'xiaohongshu'],
    is_exclusive_partner: false,
    cover_images: [],
    contact_info: { phone: '15612345678', wechat: 'niyu_pottery' },
    therapist_name: '孙艺泥',
    therapist_intro: '青年陶艺家，艺术治疗在读研究生。将传统陶艺与现代疗愈理念结合，创造独特的触觉疗愈体验。',
    feature_tags: ['触觉体验', '作品可带走', '亲子友好', '周末开放'],
    mood_tags: ['减压', '专注力', '亲子互动', '创造力'],
    per_person: 168,
    packages: [
      { name: '手工拉坯体验', price: 128, unit: '人', desc: '90分钟拉坯入门+作品带走', hot: true },
      { name: '泥塑主题创作', price: 168, unit: '人', desc: '2小时主题泥塑创作课' },
      { name: '亲子双人工坊', price: 258, unit: '组', desc: '90分钟亲子共创，含烧制' },
    ],
    resource_type: 'workshop',
    sort_weight: 72,
    likes_count: 389,
  },
  {
    _id: 'res_015',
    name: '山海·户外正念徒步',
    description: '将正念冥想与户外徒步结合的独特疗愈体验。在上海周边山林、湿地等自然环境中，通过行走冥想、自然观察、森林疗愈等方式，重建与自然和自我的连接。',
    address_text: '上海及周边（每期不同路线）',
    district: '',
    city: '上海',
    ratingNum: 4.8,
    review_count: 43,
    tags: ['冥想正念', '户外疗愈', '森林疗愈'],
    therapy_categories: ['冥想正念'],
    formats: ['沙龙'],
    price_min: 258,
    price_max: 458,
    price_text: '¥258-458/次',
    price_range: 'mid',
    certification_level: 'experienced',
    certifications: ['森林疗愈师认证', '户外运动指导员'],
    source_platforms: ['xiaohongshu'],
    is_exclusive_partner: false,
    cover_images: [],
    contact_info: { phone: '', wechat: 'shanhai_hike' },
    therapist_name: '吴山海',
    therapist_intro: '森林疗愈师，户外运动爱好者。曾在日本学习森林浴疗法，将其与正念冥想结合，已组织100+期户外正念徒步活动。',
    feature_tags: ['亲近自然', '户外活动', '每月不同路线', '摄影友好'],
    mood_tags: ['都市疲惫', '断联自然', '减压', '生命力恢复'],
    per_person: 298,
    packages: [
      { name: '半日正念徒步', price: 258, unit: '人', desc: '4小时自然疗愈行走', hot: true },
      { name: '全日深度徒步', price: 358, unit: '人', desc: '8小时正念行走+素食午餐' },
      { name: '过夜自然营', price: 458, unit: '人', desc: '两天一夜沉浸自然' },
    ],
    resource_type: 'workshop',
    sort_weight: 76,
    likes_count: 567,
  },
  {
    _id: 'res_016',
    name: '自然呼吸·人本疗愈工作室',
    description: '我们旨在创造一种自然、灵动的疗愈体验，希望通过OH卡、颂钵、冥想、唱诵等不同形式的身心探索工具，启发大家自我觉察、自我知、自我成长，完成生命能量的唤醒，实现理想人生。',
    address_text: '暂无',
    district: '暂无',
    city: '上海',
    ratingNum: 4.9,
    review_count: 56,
    tags: ['OH卡', '颂钵', '冥想'],
    therapy_categories: ['疗愈活动策划'],
    formats: ['工作坊','沙龙', '企业团建'],
    price_min: 198,
    price_max: 688,
    price_text: '定制',
    price_range: 'mid',
    certification_level: 'certified',
    certifications: ['尼泊尔NSBA认证颂钵疗愈师'],
    source_platforms: ['dianping', 'partner'],
    is_exclusive_partner: true,
    cover_images: ['https://picui.ogmua.cn/s1/2026/03/07/69abb6d98a6cd.webp'],
    contact_info: { wechat: 'asetree' },
    therapists: [
      { name: '@不不不一定', title: '风格鬼马犀利的人生教练', intro: '擅长启发式的认知提问，在深度对话中引领大家实现生命蜕变。'},
      { name: '@树里Asc', title: '风格锐利柔和的疗愈师', intro: '擅长精微细腻的洞察，帮助人从低谷的能量状态中恢复重建。', certifications: ['尼泊尔NSBA认证颂钵疗愈师'] },
    ],
    feature_tags: ['以心为引 支持共创专属疗愈主题','团体疗愈活动策划&执行'],
    mood_tags: ['减压', '焦虑缓解', '自我探索'],
    per_person: 382,
    packages: [],
    resource_type: 'studio',
    sort_weight: 100,
    likes_count: 234,
  },
  {
    _id: 'res_017',
    name: '遇见心理咨询颂钵疗愈',
    description: '提供抚触、颂钵、心理咨询等多种疗愈服务，让人感到被关爱，被安抚，从而启动人体自然的修复能力，恢复身心平衡。',
    address_text: '虹口区花园路16号(嘉和国际大夏东楼)2604室，地铁8、3号线7号口(乘直达电梯)出，步行150米',
    district: '虹口区',
    city: '上海',
    ratingNum: 4.9,
    review_count: 56,
    tags: ['抚触疗愈', '颂钵音疗', '心理咨询'],
    therapy_categories: ['颂钵音疗','心理咨询'],
    formats: ['1v1'],
    price_min: 198,
    price_max: 688,
    price_text: '人均￥382/次',
    price_range: 'mid',
    certification_level: 'certified',
    certifications: ['中科院心理咨询师', '高级颂钵疗愈师','高级抚触疗愈师'],
    source_platforms: ['dianping', 'partner'],
    is_exclusive_partner: true,
    cover_images: ['https://picui.ogmua.cn/s1/2026/03/07/69abbdb9a03b9.webp'],
    contact_info: { phone: '18930771451'},
    therapists: [
      { name: '韩媛', title: '中科院心理咨询师，', intro: '从自己的经历中生长出力量的践行者。从业十余年，累计个案数9000+小时。'},
      { name: '胡淑勤', title: '遇见心理创始人', intro: '高级抚触疗愈师,心理咨询师,高级舞动疗愈师' },
      { name: '张历红', title: '资深心理咨询师', intro: '国家二级心理咨询师，擅长自我成长、抑郁症焦虑症的咨询评估、两性关系、亲子教育(儿童与青少年)的家长议题、原生家庭解析、婚姻家庭的咨询与治疗、CBT认知行为疗法等擅长领域'},
    ],
    feature_tags: ['抚触疗愈','身心养护','颂钵疗愈','心理咨询'],
    mood_tags: ['减压', '焦虑缓解', '自我探索'],
    per_person: 382,
    packages: [
      { name: '心理咨询60分钟', price: 480, unit: '次', hot: true},
      { name: '心理咨询60分钟+ 1V1颂钵疗愈60分钟', price: 560, unit: '次' },
      { name: '1V1颂钵疗愈60分钟', price: 360, unit: '次'},
      { name:'职业规划&天赋才华咨询60分钟',price: 488,unit:'次'},
      { name:'情绪压力,艺术疗愈个案60分钟',price: 488,unit:'次'},
      { name:'情绪OH卡体验/情绪疏导60分钟',price:398,unit:'次'}],
    resource_type: 'studio',
    sort_weight: 100,
    likes_count: 234,
  },
]

// 筛选选项配置
const FILTER_CONFIG = {
  categories: [
    { id: 'all', name: '全部', icon: '🏠' },
    { id: '绘画疗愈', name: '绘画疗愈', icon: '🎨' },
    { id: '音乐疗愈', name: '音乐疗愈', icon: '🎵' },
    { id: '颂钵音疗', name: '颂钵音疗', icon: '🔔' },
    { id: '舞动疗愈', name: '舞动疗愈', icon: '💃' },
    { id: '戏剧疗愈', name: '戏剧疗愈', icon: '🎭' },
    { id: '冥想正念', name: '冥想正念', icon: '🧘' },
    { id: '芳香疗愈', name: '芳香疗愈', icon: '🌿' },
    { id: '塔罗占卜', name: '塔罗占卜', icon: '🔮' },
    { id: '瑜伽', name: '瑜伽', icon: '🧘‍♀️' },
    { id: '心理咨询', name: '心理咨询', icon: '💬' },
  ],
  priceRanges: [
    { id: 'all', label: '不限' },
    { id: 'free', label: '免费体验' },
    { id: 'low', label: '¥0-200' },
    { id: 'mid', label: '¥200-500' },
    { id: 'high', label: '¥500-1000' },
    { id: 'premium', label: '¥1000+' },
  ],
  formats: [
    { id: 'all', label: '不限' },
    { id: '工作坊', label: '工作坊' },
    { id: '1v1', label: '1v1 私教' },
    { id: '沙龙', label: '沙龙体验' },
    { id: '企业团建', label: '企业团建' },
    { id: '线上课程', label: '线上课程' },
  ],
  levels: [
    { id: 'all', label: '不限' },
    { id: 'certified', label: '持证认证' },
    { id: 'experienced', label: '经验丰富' },
    { id: 'emerging', label: '新锐疗愈师' },
  ],
  sources: [
    { id: 'all', label: '不限' },
    { id: 'partner', label: '🤝 独家合作' },
    { id: 'xiaohongshu', label: '📕 小红书' },
    { id: 'dianping', label: '⭐ 大众点评' },
  ],
  sortOptions: [
    { id: 'recommended', label: '综合推荐' },
    { id: 'rating', label: '评分最高' },
    { id: 'priceLow', label: '价格最低' },
    { id: 'priceHigh', label: '价格最高' },
    { id: 'popular', label: '最受欢迎' },
  ],
}

module.exports = { sampleResources, FILTER_CONFIG }
